### ISSUE TITLE
myBinder

### ISSUE THREAD

**Issue by ericECmorlaix** [g-vidal/CahierDeProgrammes#36]
Bonjour
Merci pour tous vos cours d'ISN-ICN que vous déposez sur GitHub. Je m'en inspire beaucoup en ce moment...
Concernant les notebook jupyter, j'utilise maintenant : https://mybinder.org/
qui permet de partager un notebook jupyter de façon interactive et dynamique tel que :
https://mybinder.org/v2/gh/ericECmorlaix/mesBN/master
Après avoir ouvert cette URL, vous verrez apparaître un explorateur jupyter du répertoire Github que je destine à mes élèves.
Double-cliquez alors par exemple sur le fichier ``ISN-Python3-index.ipynb`` pour ouvrir une instance de ce bloc-note dans un environnement interactif de jupyter notebook.
C'est le fichier ``environment.yml`` qui indique à Binder comment configurer la machine virtuelle avec les bibliothèques utiles.
http://icn.cpn56.fr/2018/01/mybinder/

Merci encore pour le partage de vos travaux...
@+
eric.madec@ecmorlaix.fr

**Comment by ericlejan** [comment]
Bonjour,

Merci pour votre commentaire et votre lien. Votre cahier à propos de Latex est très intéressant. 
Je suis prof de SVT, ce qui fait que je ne maitrise par bien ce mode d'édition, les liens sont une très bonne ressource. 

Eric Le Jan.

**Comment by ericECmorlaix** [comment]
Bonjour

Merci pour vos encouragements, je suis prof de Sciences de l’Ingénieur et d’ISN-ICN. J’ai découvert LaTeX avec mes collègues de Math mais surtout grâce à une ancienne élève qui une fois dans le supérieur m’a recommandé d’en faire au lycée. J’ai donc développé une séquence d’AP sur ce sujet : http://tsi.si.lycee.ecmorlaix.fr/APprentissageLaTeX/. J’ai mis là de nombreux autres liens…

Depuis que j’ai découvert les bloc-notes jupyter avec la possibilité de les partager en mode interactif avec myBinder depuis un compte GitHub, je me dis que c’est un super outil pour réaliser des comptes rendus d’expérience scientifique au lycée dès la seconde…

A bientôt pour de nouveaux échanges.

@+
Eric MADEC



De : Eric Le Jan [mailto:notifications@github.com]
Envoyé : dimanche 4 février 2018 11:21
À : g-vidal/CahierDeProgrammes <CahierDeProgrammes@noreply.github.com>
Cc : Eric MADEC <eric.madec@ecmorlaix.fr>; Author <author@noreply.github.com>
Objet : Re: [g-vidal/CahierDeProgrammes] myBinder (#36)


Bonjour,

Merci pour votre commentaire et votre lien. Votre cahier à propos de Latex est très intéressant.
Je suis prof de SVT, ce qui fait que je ne maitrise par bien ce mode d'édition, les liens sont une très bonne ressource.

Eric Le Jan.

**Comment by g-vidal** [comment]
Bonjour,

Merci de votre contribution. 
Dans notre projet nous avons fait le choix de travailler avec des capteurs et des effecteurs "réels" (tangibles) qui permettent aux élèves/étudiants de manipuler les leds, les capteurs et autres montages dans une situation concrète et sans couche intermédiaire susceptible de masquer le fonctionnement réel du dispositif. L'un des objectifs est de faire comprendre le fonctionnement et l'empilement de couches logicielles  permettant de disposer de systèmes conviviaux mais contraints. Pour cela nous devons déployer ces cahiers de programme sur une Raspberry Pi ou tout autre SOC contrôlant un GPIO (INTEL Edison, beagle Bone Odroïd...). Nous proposons pour cela une  [image de RaspberryPi](http://mediaserv.climatetmeteo.fr/images/RaspBerry/). Il me semble donc que l'incorporation de votre proposition dans le master pourrait désorienter  un utilisateur non averti  qui ne comprendrait pas pourquoi rien ne fonctionne.... et c'est avec plairir que nous vous proposerons les mises à jour pour le fork myBinder que vous avez créé.

Nous essayons d'améliorer la restitution en pdf et nous cherchons à ajouter un footer avec des images sur des pages A4 en français. Si vous avez une proposition de .tplx qui ferait le boulot cela nous aiderait beaucoup.
